In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

Array: [1 2 3 4 5]


In [2]:
import numpy as np

print("Zeros:\n", np.zeros((2,3)))
print("Ones:\n", np.ones((3,3)))
print("Identity Matrix:\n", np.eye(3))

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
import numpy as np

print("Using arange:", np.arange(1, 10, 2))
print("Using linspace:", np.linspace(0, 1, 5))

Using arange: [1 3 5 7 9]
Using linspace: [0.   0.25 0.5  0.75 1.  ]


In [4]:
import numpy as np

arr = np.arange(1, 10)
reshaped = arr.reshape(3,3)
print(reshaped)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice:", arr[1:4])

First element: 10
Last element: 50
Slice: [20 30 40]


In [6]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [7]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Sum:", np.sum(arr))

Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Sum: 150


In [8]:
import numpy as np

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Matrix Multiplication:\n", np.dot(A,B))

Matrix Multiplication:
 [[19 22]
 [43 50]]


In [9]:
import numpy as np

A = np.array([[1,2,3],[4,5,6]])
print("Transpose:\n", A.T)

Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [10]:
import numpy as np

print("Random Numbers:", np.random.rand(5))
print("Random Integers:", np.random.randint(1, 10, 5))

Random Numbers: [0.30046574 0.67629925 0.08816165 0.7655965  0.30869949]
Random Integers: [3 5 9 8 6]


In [11]:
import numpy as np

arr = np.array([5, 10, 2, 8, 15])

print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Index of Max:", np.argmax(arr))

Max: 15
Min: 2
Index of Max: 4


In [12]:
import numpy as np

arr = np.array([5, 2, 9, 1])
print("Sorted:", np.sort(arr))

Sorted: [1 2 5 9]


In [13]:
arr = np.array([10, 20, 30, 40, 50])
print("Elements > 25:", arr[arr > 25])

Elements > 25: [30 40 50]


In [14]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Concatenated:", np.concatenate((a,b)))

Concatenated: [1 2 3 4 5 6]


In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Vertical Stack:\n", np.vstack((a,b)))
print("Horizontal Stack:\n", np.hstack((a,b)))

Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]


In [16]:

arr = np.array([1,2,2,3,4,4,5])
print("Unique Elements:", np.unique(arr))

Unique Elements: [1 2 3 4 5]


In [17]:
A = np.array([[3,1],[1,2]])
B = np.array([9,8])

X = np.linalg.solve(A,B)
print("Solution:", X)

Solution: [2. 3.]


In [18]:
A = np.array([[1,2],[3,4]])

print("Determinant:", np.linalg.det(A))
print("Inverse:\n", np.linalg.inv(A))

Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [19]:
arr = np.array([1,2,3])
print("Add 10 to each element:", arr + 10)

Add 10 to each element: [11 12 13]


In [20]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print("Row Sum:", np.sum(arr, axis=1))
print("Column Sum:", np.sum(arr, axis=0))

Row Sum: [ 6 15 24]
Column Sum: [12 15 18]


In [21]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("Original Array:\n", arr)
print("Flattened Array:", arr.flatten())

Original Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]


In [22]:
arr = np.array([1, 2, 3, 4])

copy_arr = arr.copy()
view_arr = arr.view()

arr[0] = 100

print("Original:", arr)
print("Copy:", copy_arr)   # Does NOT change
print("View:", view_arr)   # Changes because it shares memory

Original: [100   2   3   4]
Copy: [1 2 3 4]
View: [100   2   3   4]


In [23]:
arr = np.array([10, 15, 20, 25, 30, 35])

even = arr[arr % 2 == 0]
odd = arr[arr % 2 != 0]

print("Even Numbers:", even)
print("Odd Numbers:", odd)

Even Numbers: [10 20 30]
Odd Numbers: [15 25 35]


In [24]:
arr = np.array([5, 10, 15, 20, 25])

# Replace values greater than 15 with 100
arr[arr > 15] = 100

print("Modified Array:", arr)

Modified Array: [  5  10  15 100 100]


In [25]:
A = np.array([[4, -2],
              [1,  1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
